# Generated by Django 3.2.12 on 2022-05-05 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220429_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 17, 51, 31, 476478)),
        ),
        migrations.AlterField(
            model_name='writeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='writeruserprofile',
            name='country',
            field=models.CharField(blank=True, max_length=40, verbose_name='страна'),
        ),
    ]
