# Generated by Django 3.2.12 on 2022-05-14 02:25

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20220505_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeruser',
            name='age',
        ),
        migrations.AddField(
            model_name='writeruser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writeruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 2, 25, 20, 204713)),
        ),
        migrations.AlterField(
            model_name='writeruserprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='writeruserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mужчина'), ('W', 'Женщина')], max_length=7, verbose_name='пол'),
        ),
    ]
