# Generated by Django 3.2.12 on 2022-04-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=112, verbose_name='количество просмотров'),
            preserve_default=False,
        ),
    ]
