# Generated by Django 3.2.12 on 2022-05-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
