# Generated by Django 3.2.12 on 2022-04-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='total_views',
        ),
    ]
